export const CANONICAL_FIELDS = [
  'civility',
  'fullName',
  'lastName',
  'firstName',
  'birthName',
  'birthDate',
  'birthPlace',
  'nationality',
  'email',
  'phone',
  'phoneSecondary',
  'street',
  'street2',
  'postalCode',
  'city',
  'country',
  'addressFull',
  'housingStatus',
  'housingSince',
  'professionalStatus',
  'occupation',
  'contractType',
  'jobStartDate',
  'employerName',
  'employerAddress',
  'employerPhone',
  'employerEmail',
  'netMonthlyIncome',
  'grossMonthlyIncome',
  'annualIncome',
  'otherIncome',
  'otherIncomeDescription',
  'peopleCount',
  'childrenCount',
  'maritalStatus',
  'iban',
  'bic',
  'bankName',
  'currentRent',
  'desiredMoveDate',
  'desiredCity',
  'notes',
] as const

export type CanonicalKey = (typeof CANONICAL_FIELDS)[number]

export interface CanonicalFieldMeta {
  key: CanonicalKey
  labelFr: string
  category: string
  inputHints: string[]
}

export const CANONICAL_META: Record<CanonicalKey, CanonicalFieldMeta> = {
  civility: {
    key: 'civility',
    labelFr: 'Civilité',
    category: 'identité',
    inputHints: ['select', 'radio'],
  },
  fullName: {
    key: 'fullName',
    labelFr: 'Nom complet',
    category: 'identité',
    inputHints: ['text'],
  },
  lastName: {
    key: 'lastName',
    labelFr: 'Nom de famille',
    category: 'identité',
    inputHints: ['text'],
  },
  firstName: {
    key: 'firstName',
    labelFr: 'Prénom',
    category: 'identité',
    inputHints: ['text'],
  },
  birthName: {
    key: 'birthName',
    labelFr: 'Nom de naissance',
    category: 'identité',
    inputHints: ['text'],
  },
  birthDate: {
    key: 'birthDate',
    labelFr: 'Date de naissance',
    category: 'identité',
    inputHints: ['date', 'text'],
  },
  birthPlace: {
    key: 'birthPlace',
    labelFr: 'Lieu de naissance',
    category: 'identité',
    inputHints: ['text'],
  },
  nationality: {
    key: 'nationality',
    labelFr: 'Nationalité',
    category: 'identité',
    inputHints: ['text', 'select'],
  },
  email: {
    key: 'email',
    labelFr: 'E-mail',
    category: 'contact',
    inputHints: ['email'],
  },
  phone: {
    key: 'phone',
    labelFr: 'Téléphone',
    category: 'contact',
    inputHints: ['tel'],
  },
  phoneSecondary: {
    key: 'phoneSecondary',
    labelFr: 'Téléphone secondaire',
    category: 'contact',
    inputHints: ['tel'],
  },
  street: {
    key: 'street',
    labelFr: 'Adresse',
    category: 'adresse',
    inputHints: ['text'],
  },
  street2: {
    key: 'street2',
    labelFr: 'Complément d’adresse',
    category: 'adresse',
    inputHints: ['text'],
  },
  postalCode: {
    key: 'postalCode',
    labelFr: 'Code postal',
    category: 'adresse',
    inputHints: ['text', 'tel'],
  },
  city: {
    key: 'city',
    labelFr: 'Ville',
    category: 'adresse',
    inputHints: ['text'],
  },
  country: {
    key: 'country',
    labelFr: 'Pays',
    category: 'adresse',
    inputHints: ['text', 'select'],
  },
  addressFull: {
    key: 'addressFull',
    labelFr: 'Adresse complète',
    category: 'adresse',
    inputHints: ['text', 'textarea'],
  },
  housingStatus: {
    key: 'housingStatus',
    labelFr: 'Situation de logement',
    category: 'adresse',
    inputHints: ['select', 'radio'],
  },
  housingSince: {
    key: 'housingSince',
    labelFr: 'Dans le logement depuis',
    category: 'adresse',
    inputHints: ['date', 'text'],
  },
  professionalStatus: {
    key: 'professionalStatus',
    labelFr: 'Statut professionnel',
    category: 'profession',
    inputHints: ['select', 'radio', 'text'],
  },
  occupation: {
    key: 'occupation',
    labelFr: 'Profession',
    category: 'profession',
    inputHints: ['text'],
  },
  contractType: {
    key: 'contractType',
    labelFr: 'Type de contrat',
    category: 'profession',
    inputHints: ['select', 'text'],
  },
  jobStartDate: {
    key: 'jobStartDate',
    labelFr: 'Date d’embauche',
    category: 'profession',
    inputHints: ['date', 'text'],
  },
  employerName: {
    key: 'employerName',
    labelFr: 'Employeur',
    category: 'employeur',
    inputHints: ['text'],
  },
  employerAddress: {
    key: 'employerAddress',
    labelFr: 'Adresse employeur',
    category: 'employeur',
    inputHints: ['text', 'textarea'],
  },
  employerPhone: {
    key: 'employerPhone',
    labelFr: 'Téléphone employeur',
    category: 'employeur',
    inputHints: ['tel'],
  },
  employerEmail: {
    key: 'employerEmail',
    labelFr: 'E-mail employeur',
    category: 'employeur',
    inputHints: ['email'],
  },
  netMonthlyIncome: {
    key: 'netMonthlyIncome',
    labelFr: 'Revenus nets mensuels',
    category: 'revenus',
    inputHints: ['number', 'text'],
  },
  grossMonthlyIncome: {
    key: 'grossMonthlyIncome',
    labelFr: 'Revenus bruts mensuels',
    category: 'revenus',
    inputHints: ['number', 'text'],
  },
  annualIncome: {
    key: 'annualIncome',
    labelFr: 'Revenus annuels',
    category: 'revenus',
    inputHints: ['number', 'text'],
  },
  otherIncome: {
    key: 'otherIncome',
    labelFr: 'Autres revenus (panier repas, etc.)',
    category: 'revenus',
    inputHints: ['number', 'text'],
  },
  otherIncomeDescription: {
    key: 'otherIncomeDescription',
    labelFr: 'Nature des autres revenus',
    category: 'revenus',
    inputHints: ['text'],
  },
  peopleCount: {
    key: 'peopleCount',
    labelFr: 'Nombre de personnes',
    category: 'foyer',
    inputHints: ['number'],
  },
  childrenCount: {
    key: 'childrenCount',
    labelFr: 'Nombre d’enfants',
    category: 'foyer',
    inputHints: ['number'],
  },
  maritalStatus: {
    key: 'maritalStatus',
    labelFr: 'Situation familiale',
    category: 'foyer',
    inputHints: ['select', 'text'],
  },
  iban: {
    key: 'iban',
    labelFr: 'IBAN',
    category: 'banque',
    inputHints: ['text'],
  },
  bic: {
    key: 'bic',
    labelFr: 'BIC / SWIFT',
    category: 'banque',
    inputHints: ['text'],
  },
  bankName: {
    key: 'bankName',
    labelFr: 'Banque',
    category: 'banque',
    inputHints: ['text'],
  },
  currentRent: {
    key: 'currentRent',
    labelFr: 'Loyer actuel',
    category: 'logement',
    inputHints: ['number', 'text'],
  },
  desiredMoveDate: {
    key: 'desiredMoveDate',
    labelFr: 'Disponibilité',
    category: 'logement',
    inputHints: ['text', 'select'],
  },
  desiredCity: {
    key: 'desiredCity',
    labelFr: 'Ville souhaitée',
    category: 'logement',
    inputHints: ['text'],
  },
  notes: {
    key: 'notes',
    labelFr: 'Commentaire',
    category: 'autre',
    inputHints: ['textarea', 'text'],
  },
}
