import type { CanonicalKey } from './canonical'

export const SYNONYMS: Record<CanonicalKey, string[]> = {
  civility: [
    'civilite',
    'titre',
    'genre',
    'sexe',
    'title',
    'salutation',
    'honorific',
    'mr mrs',
    'monsieur madame',
  ],
  fullName: [
    'nom complet',
    'nom et prenom',
    'prenom et nom',
    'nom prenom',
    'nom et prenom du salarie',
    'full name',
    'fullname',
    'applicant name',
    'complete name',
    'votre nom',
    'name',
  ],
  lastName: [
    'nom de famille',
    'nom famille',
    'nom patronymique',
    'lastname',
    'last name',
    'surname',
    'family name',
    'familienname',
    'apellido',
    'nom',
    'nom locataire',
    'nom du locataire',
    'nom du candidat',
    'nom du garant',
    'nom du cautionnaire',
  ],
  firstName: [
    'prenom',
    'prenoms',
    'first name',
    'firstname',
    'given name',
    'givenname',
    'forename',
    'vorname',
    'nombre de pila',
  ],
  birthName: [
    'nom de naissance',
    'nom naissance',
    'nom jeune fille',
    'nom d usage',
    'maiden name',
    'birth name',
  ],
  birthDate: [
    'date de naissance',
    'ne le',
    'nee le',
    'birth date',
    'date of birth',
    'dob',
    'birthday',
    'born on',
    'geburtsdatum',
  ],
  birthPlace: [
    'lieu de naissance',
    'ville de naissance',
    'ne a',
    'nee a',
    'place of birth',
    'birth place',
    'birthplace',
    'born in',
  ],
  nationality: [
    'nationalite',
    'nationality',
    'citoyennete',
    'citizenship',
    'pays de nationalite',
  ],
  email: [
    'email',
    'e mail',
    'mail',
    'courriel',
    'adresse mail',
    'adresse email',
    'adresse e mail',
    'electronic mail',
  ],
  phone: [
    'telephone',
    'tel',
    'phone',
    'mobile',
    'portable',
    'cellphone',
    'cell phone',
    'numero de telephone',
    'phone number',
  ],
  phoneSecondary: [
    'telephone secondaire',
    'tel 2',
    'phone 2',
    'autre telephone',
    'fixe',
    'landline',
    'home phone',
    'telephone domicile',
  ],
  street: [
    'adresse',
    'rue',
    'voie',
    'numero et rue',
    'street',
    'address line 1',
    'address1',
    'street address',
    'adresse postale',
  ],
  street2: [
    'complement',
    'complement adresse',
    'batiment',
    'appartement',
    'address line 2',
    'address2',
    'apt',
    'suite',
    'residence',
  ],
  postalCode: [
    'code postal',
    'cp',
    'postal code',
    'zip',
    'zip code',
    'postcode',
    'plz',
  ],
  city: [
    'ville',
    'commune',
    'localite',
    'city',
    'town',
    'municipality',
  ],
  country: ['pays', 'country', 'nation', 'etat'],
  addressFull: [
    'adresse complete',
    'full address',
    'adresse actuelle',
    'current address',
    'domicile',
    'demeurant',
  ],
  housingStatus: [
    'situation logement',
    'statut logement',
    'occupant',
    'locataire ou proprietaire',
    'housing status',
    'residential status',
    'vous etes',
  ],
  housingSince: [
    'date de prise de ce logement',
    'date emmenagement',
    'habite depuis',
    'occupant depuis',
    'dans le logement depuis',
    'moved in',
    'living there since',
  ],
  professionalStatus: [
    'statut professionnel',
    'situation actuelle',
    'situation pro',
    'categorie socio',
    'emploi statut',
    'employment status',
    'occupational status',
  ],
  occupation: [
    'profession',
    'metier',
    'poste occupe',
    'job title',
    'occupation',
    'intitule de poste',
    'emploi qualification',
  ],
  contractType: [
    'type de contrat',
    'nature du contrat',
    'contract type',
    'employment contract',
  ],
  jobStartDate: [
    'date embauche',
    'date de l embauche',
    'date de l embauche/retraite',
    'date d entree',
    'en poste depuis',
    'anciennete',
    'start date',
    'employed since',
    'hire date',
  ],
  employerName: [
    'employeur',
    'nom de l entreprise',
    'nom de la societe',
    'raison sociale',
    'company',
    'employer',
    'organization',
    'nom de l employeur',
  ],
  employerAddress: [
    'adresse employeur',
    'adresse entreprise',
    'siege social',
    'employer address',
    'company address',
    'lieu de travail du salarie',
  ],
  employerPhone: [
    'telephone employeur',
    'tel employeur',
    'tel societe',
    'employer phone',
    'company phone',
  ],
  employerEmail: [
    'email employeur',
    'mail employeur',
    'employer email',
    'company email',
    'rh email',
  ],
  netMonthlyIncome: [
    'salaire net',
    'revenu net',
    'revenus nets',
    'net mensuel',
    'salaire mensuel net',
    'ressources mensuelles',
    'revenus mensuels',
    'monthly net',
    'net income',
    'take home',
    'net a payer',
  ],
  grossMonthlyIncome: [
    'salaire brut',
    'salaire de base',
    'salaire de base mensuel brut',
    'brut mensuel',
    'gross monthly',
    'gross income',
    'monthly gross',
  ],
  annualIncome: [
    'revenu annuel',
    'revenus annuels',
    'salaire annuel',
    'annual income',
    'yearly income',
    'revenu fiscal',
    'rfrc',
  ],
  otherIncome: [
    'autres revenus',
    'autres ressources',
    'autres ressources preciser',
    'revenus annexes',
    'panier repas',
    'tickets restaurant',
    'titres restaurant',
    'avantages en nature',
    'other income',
    'additional income',
  ],
  otherIncomeDescription: [
    'nature des revenus',
    'precision revenus',
    'source autres revenus',
    'income description',
  ],
  peopleCount: [
    'nombre de personnes',
    'nb personnes',
    'occupants',
    'household size',
    'number of occupants',
    'composition foyer',
  ],
  childrenCount: [
    'nombre d enfants',
    'nb enfants',
    'enfants a charge',
    'children',
    'dependents',
    'nombre d enfants a charge',
  ],
  maritalStatus: [
    'situation familiale',
    'situation maritale',
    'statut marital',
    'marital status',
    'family status',
  ],
  iban: ['iban', 'identifiant bancaire', 'account number iban'],
  bic: ['bic', 'swift', 'code bic', 'swift code'],
  bankName: ['banque', 'etablissement bancaire', 'bank', 'bank name'],
  currentRent: [
    'loyer actuel',
    'loyer en cours',
    'current rent',
    'monthly rent',
    'montant du loyer',
  ],
  desiredMoveDate: [
    'date emmenagement',
    'date d entree souhaitee',
    'disponibilite',
    'disponible',
    'move in date',
    'desired date',
    'entree des lieux',
    'emmenagement',
    'available from',
    'availability',
    'asap',
    'immediat',
    'tout de suite',
  ],
  desiredCity: [
    'ville souhaitee',
    'secteur',
    'ville recherchee',
    'desired city',
    'preferred city',
  ],
  notes: [
    'commentaire',
    'message',
    'informations complementaires',
    'remarks',
    'notes',
    'additional information',
    'precisions',
  ],
}

export const AUTOCOMPLETE_MAP: Record<string, CanonicalKey> = {
  'given-name': 'firstName',
  'family-name': 'lastName',
  'additional-name': 'birthName',
  'honorific-prefix': 'civility',
  email: 'email',
  'tel': 'phone',
  'tel-national': 'phone',
  'tel-local': 'phone',
  'street-address': 'addressFull',
  'address-line1': 'street',
  'address-line2': 'street2',
  'postal-code': 'postalCode',
  'address-level2': 'city',
  country: 'country',
  'country-name': 'country',
  'organization': 'employerName',
  'bday': 'birthDate',
  'bday-day': 'birthDate',
}

export const TYPE_HINTS: Record<string, CanonicalKey[]> = {
  email: ['email', 'employerEmail'],
  tel: ['phone', 'phoneSecondary', 'employerPhone'],
  date: ['birthDate', 'jobStartDate', 'housingSince', 'desiredMoveDate'],
  number: [
    'netMonthlyIncome',
    'grossMonthlyIncome',
    'annualIncome',
    'otherIncome',
    'peopleCount',
    'childrenCount',
    'currentRent',
    'postalCode',
  ],
}

export const OPTION_HINTS: { key: CanonicalKey; patterns: RegExp }[] = [
  {
    key: 'civility',
    patterns: /\b(m\.?|mme|mlle|mr|mrs|ms|monsieur|madame|mx)\b/i,
  },
  {
    key: 'contractType',
    patterns: /\b(cdi|cdd|interim|freelance|alternance|stage)\b/i,
  },
  {
    key: 'housingStatus',
    patterns: /\b(locataire|proprietaire|heberge|hosted|owner|tenant)\b/i,
  },
  {
    key: 'professionalStatus',
    patterns: /\b(salarie|independant|etudiant|retraite|sans emploi|employee|self[- ]employed|student)\b/i,
  },
  {
    key: 'maritalStatus',
    patterns: /\b(celibataire|marie|pacse|divorce|veuf|single|married|civil union)\b/i,
  },
]

export const SECTION_HINTS: { pattern: RegExp; boost: CanonicalKey[] }[] = [
  {
    pattern: /employeur|employer|societe|company|entreprise|situation professionnelle/i,
    boost: [
      'employerName',
      'employerAddress',
      'employerPhone',
      'employerEmail',
      'occupation',
      'contractType',
      'jobStartDate',
      'professionalStatus',
      'grossMonthlyIncome',
    ],
  },
  {
    pattern: /identite|identity|etat civil|personal/i,
    boost: ['civility', 'firstName', 'lastName', 'birthDate', 'birthPlace', 'nationality'],
  },
  {
    pattern: /contact|coordonnees/i,
    boost: ['email', 'phone', 'phoneSecondary'],
  },
  {
    pattern: /adresse|address|domicile|logement actuel/i,
    boost: ['street', 'street2', 'postalCode', 'city', 'country', 'addressFull'],
  },
  {
    pattern: /revenu|salaire|income|ressources/i,
    boost: ['netMonthlyIncome', 'grossMonthlyIncome', 'annualIncome', 'otherIncome'],
  },
  {
    pattern: /banque|bank|paiement|payment/i,
    boost: ['iban', 'bic', 'bankName'],
  },
  {
    pattern: /foyer|household|famille|family/i,
    boost: ['peopleCount', 'childrenCount', 'maritalStatus'],
  },
]
